apiVersion: v1
kind: PersistentVolume
metadata:
  name: factorio-live-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.123.17
    path: /mnt/ISOs/factorio-live
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: factorio-live-data
spec:
  accessModes:
    - ReadWriteMany
  volumeName: factorio-live-pv
  resources:
    requests:
      storage: "5Gi"
